CREATE TABLE IF NOT EXISTS NEWPROJECT.RAW.NEWCICDCUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CREATED_DATE DATE
);
CREATE TABLE IF NOT EXISTS NEWPROJECT.RAW.NEWCICDORDERS
(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    ORDER_AMOUNT NUMBER(18,2)
);
CREATE OR REPLACE VIEW NEWPROJECT.RAW.NEWCUSTOMER_ORDERS_VW AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    o.ORDER_ID,
    o.ORDER_DATE,
    o.ORDER_AMOUNT
FROM NEWPROJECT.RAW.CUSTOMERS c
LEFT JOIN NEWPROJECT.RAW.NEWCICDORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID;