CREATE OR REPLACE VIEW NEWPROJECT.RAW.CUSTOMER_ORDERS_VW AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    o.ORDER_ID,
    o.ORDER_DATE,
    o.ORDER_AMOUNT
FROM NEWPROJECT.RAW.CUSTOMERS c
LEFT JOIN NEWPROJECT.RAW.CICDORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID;