CREATE TABLE IF NOT EXISTS NEWPROJECT.RAW.CICDCUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CREATED_DATE DATE
);
CREATE TABLE IF NOT EXISTS NEWPROJECT.RAW.CICDORDERS
(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    ORDER_AMOUNT NUMBER(18,2)
);